name: Automate terraform linting using terraform fmt 

on: 
   push: 
   workflow_dispatch:
    inputs: 
     terraform command: 
      description: 'choose terraform command to run'
      required: true 
      type: choice
      options: 
       - terraform apply
       - Automate terraform linting using terraform fmt
       - terraform destroy 
  

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: connect to aws 
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Terraform init
        run: terraform init
       
      - name: terraform fmt 
        run: terraforom fmt -check 

      - name: terraform validate 
        run: terraform validate 

      - name: Terraform plan
        run: terraform plan